# Generated by Django 3.0.6 on 2020-05-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_agent',
            field=models.BooleanField(null=True),
        ),
    ]
